on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install UV and dependencies
        run: 
          python -m pip install --upgrade pip
          pip install uv
          uv sync --all-extras

      - name: Run ruff lint and auto-fix
        run: ruff check . --fix

      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q
